// <auto-generated />
using System;
using Human_Resource_Generator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Human_Resource_Generator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230401080031_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Human_Resource_Generator.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.EmployeeTraining", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProgramId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmployeeId", "ProgramId");

                    b.HasIndex("ProgramId");

                    b.ToTable("EmployeeTrainings");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.TrainingProgram", b =>
                {
                    b.Property<string>("program_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date_of_program")
                        .HasColumnType("datetime2");

                    b.Property<string>("program_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("program_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("program_id");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.EmployeeTraining", b =>
                {
                    b.HasOne("Human_Resource_Generator.Models.Employee", "Employee")
                        .WithMany("EmployeeTrainings")
                        .HasForeignKey("EmployeeId")
                        .IsRequired();

                    b.HasOne("Human_Resource_Generator.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("EmployeeTrainings")
                        .HasForeignKey("ProgramId")
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.Employee", b =>
                {
                    b.Navigation("EmployeeTrainings");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.TrainingProgram", b =>
                {
                    b.Navigation("EmployeeTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
